### PR TITLE
Fix for focus events on iOS

### PR DESCRIPTION
**Pull request by AnthonyNjuguna**
Fix for issue #2

### CODE REVIEW

**Comment by ChaseFlorell** [comment]
Did you test this and confirm that the events are raised and the property is updated?

**Comment by AnthonyNjuguna** [comment]
Yes I did - you can test it on the branch - however I only fixed it on iOS was this an issue on Android too?

**Comment by ChaseFlorell** [comment]
Yes, it's a todo on both platforms. I'm pretty sure I tested the approach you did and didn't have success with the events being raised, or the `IsFocused` being toggled... or something... can't remember.

**Comment by ChaseFlorell** [comment]
@AnthonyNjuguna I'm testing this on iOS and am not having any success. I'm wondering if there's anything else you've done to get these calls working in your environment? I'm testing this in my iOS Simulator.

```xml
<xfx:XfxComboBox Grid.Row="0"
                    Grid.Column="1"
                    Focused="EmailAddress_OnFocused"
                    Unfocused="EmailAddress_OnUnfocused"
                    Placeholder="Enter your email address"
                    Text="{Binding EmailAddress}"
                    ItemsSource="{Binding EmailSuggestions}"
                    SortingAlgorithm="{Binding SortingAlgorithm}" />
```

```csharp
private void EmailAddress_OnFocused(object sender, FocusEventArgs e)
{
    Debug.WriteLine("EmailAddress Focused"); // never runs
}

private void EmailAddress_OnUnfocused(object sender, FocusEventArgs e)
{
    Debug.WriteLine("EmailAddress Unfocused"); // never runs
}
```

**Comment by ChaseFlorell** [comment]
Fixed in af4c8f1677a8756527dee5bebeffb89656cf8ae8

**Comment by AnthonyNjuguna** [comment]
@ChaseFlorell Apologies, for some reason I was not getting notifications on any of your comments. I came to check the progress of the pull request to find open questions. 
I'm glad you managed to fix it - I can't fathom why my changes were working for me and not for you. 
Good fix  👍

**Comment by ChaseFlorell** [comment]
@AnthonyNjuguna no problem. The only thing I can think of is you might have something else wired in there masking it (I've seen people extend with their own events to work around Xam internals quite a bit). If you look at the change source, I had to use reflection to extract the value of the internal field, and then use the standard Xamarin approach to do the value update.

**Pull request closed without merging**
